### ISSUE TITLE
about wasserstein dro

### ISSUE THREAD

**Issue by Ouyang-maxzx** [zhengang-zhong/distributionally_robust_optimization#1]
Dr.Zhong
       我目前在研究分布鲁棒优化在电力系统中的应用，但是困惑于不知道如何将原问题转化为对偶问题进行求解，我想从您的代码里面进行学习，这个代码有没有对应的文献，我想配套着进行学习。

**Comment by zhengang-zhong** [comment]
您好, 我这个repository中复现了"Data-driven distributionally robust optimization using the Wasserstein metric: performance guarantees and tractable reformulations"和“Distributionally robust control of constrained stochastic systems”两篇文章. 

关于这里的对偶问题可以通过第一篇复现文章学习. 在Th4.2中根据Wasserstein metric的定义以及duality, 将优化问题变成了几个minimax ineqaulity, 然后借助假设以及几篇经典文章的结论证明了strong duality.

如果是针对电力系统,我推荐阅读“Robust Optimization in Electric Energy Systems”.这本书也有关于除了Wasserstein以外不同distance的DRO问题的duality形式的简化推导.

**Comment by Ouyang-maxzx** [comment]
您好，非常感谢您的推荐，我会继续研究，虽然对于我来说有点困难。
