### ISSUE TITLE
dro

### ISSUE THREAD

**Issue by Ouyang-maxzx** [zhengang-zhong/distributionally_robust_optimization#2]
Dr.Zhong
     您好，我在编程过程中，产生一些疑问，想请教你一下，我的不确定性变量是1*24的，那么我用wasserstein来刻度的话，所得到那个半径是不是也应该是1*24个，这样来解决这个问题吗？因为我之前看https://github.com/linfengYang/Wasserstein-DRO-self-scheduling-model，这个代码他求半径的方法很奇怪，最后也只得到一个半径。

**Comment by zhengang-zhong** [comment]
您好,
这个问题取决于DRO中uncertainty的形式. 如果将124个uncertainty variables当作一个uncertainty vector, 这时候只需要一个Wasserstein ball 也就是一个半径.

**Comment by Ouyang-maxzx** [comment]
> 您好， 这个问题的原稿是 RO 中的不确定性的形式。如果将 124 个不确定变量也用作一个不确定向量，那么此时只需要一个 Wasserstein ball 就是一个半径。

您好，就是可以把公式里面变量看成向量的形式，另外的话，我还有个问题，看了很多文献，对于不等式约束里面或者等式约束里面含有不确定性变量没有一个具体的推导形式或者说处理方法，因此想请教下您，，不等式约束中含有不确定性变量，可以通过条件风险价值近似的·方式，但是如果是等式约束含有不确定性量应该如何处理

**Comment by zhengang-zhong** [comment]
您好, 如果是non-data-driven robust optimization或者distribuitonally robust optimization的话, 带有不确定性变量的inequality constraint可以变成robust counterpart. 具体见"Deriving robust counterparts of nonlinear uncertain inequalities". 如果是data-driven DRO问题, 例如使用Wasserstein distance的几篇论文, uncertainty一般以data的形式出现在inequality constraint中.

**Comment by Ouyang-maxzx** [comment]
您好， ’‘uncertainty一般以data的形式出现在inequality constraint中.‘’，这句话是不是指的是，对含不确定性变量目标函数进行转换得到milp，其中里面有关于wasserstein的inequality constraint ，我不明白的是，如果我原本的约束里面就含有不确定性变量，这个constraint应该如何处理。

**Comment by zhengang-zhong** [comment]
请问有具体例子吗?

**Comment by Ouyang-maxzx** [comment]
您好，具体例子的话，这个文献，Optimal scheduling for microgrids with hydrogen fueling stations considering uncertainty using data-driven approach，见公式61，63.

**Comment by zhengang-zhong** [comment]
61的公式是uncertainty的support set, 意思是所有的uncertainty realization都取自这个support set. 这样的DRO问题可以通过取uncertainty samples作为empirical distribution用于构造Wasserstein ball. 然后通过duality将DRO问题变成63的公式. 具体变换过程见Data-driven distributionally robust optimization using the Wasserstein metric: performance guarantees and tractable reformulations的Corollary 5.1和Theorem 4.2.
