### ISSUE TITLE
您好,

### ISSUE THREAD

**Issue by Ouyang-maxzx** [zhengang-zhong/distributionally_robust_optimization#3]
您好,
这个问题取决于DRO中uncertainty的形式. 如果将124个uncertainty variables当作一个uncertainty vector, 这时候只需要一个Wasserstein ball 也就是一个半径.

_Originally posted by @zhengang-zhong in https://github.com/zhengang-zhong/distributionally_robust_optimization/issues/2#issuecomment-1104481161_

**Comment by Ouyang-maxzx** [comment]
您好，把变量看成一个uncertainty vector（1*24），只有一个半径，在转化过后的目标函数里面，这个变量应该是一个什么维度的矩阵，非常期待您的回复，我在编程的时候求解，提示我这个地方目标函数是无界的。
![image](https://user-images.githubusercontent.com/73262881/165877452-65b352cd-1467-49fb-ae81-e32cabec19bd.png)

**Comment by zhengang-zhong** [comment]
kappa_i 就是一个1维的标量. 但是你有N个kappa对应你每个sample.

**Comment by Ouyang-maxzx** [comment]
您好，非常谢谢您，kappa—i是一个1维标量。
